version: "3"
services:
  postgresql:
    image: "postgres:latest"
    hostname: "postgresql"
    container_name: "postgresql"
    environment:
      POSTGRES_PASSWORD: "INSECURE"
      POSTGRES_USER: "wobbly"
      POSTGRES_DB: "wobbly"
    ports:
      - "5432:5432"
